window["document"]["writeln"]("<link rel=\'canonical\' href=\'https://getbootstrap.com/docs/4.4/examples/cover/\'>");
window["document"]["writeln"]("    <!-- Bootstrap core CSS -->");
window["document"]["writeln"]("    <link rel=\'stylesheet\' href=\'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\' integrity=\'sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\' crossorigin=\'anonymous\'>");
window["document"]["writeln"]("");
window["document"]["writeln"]("    <style>");
window["document"]["writeln"]("      .bd-placeholder-img {");
window["document"]["writeln"]("        font-size: 1.125rem;");
window["document"]["writeln"]("        text-anchor: middle;");
window["document"]["writeln"]("        -webkit-user-select: none;");
window["document"]["writeln"]("        -moz-user-select: none;");
window["document"]["writeln"]("        -ms-user-select: none;");
window["document"]["writeln"]("        user-select: none;");
window["document"]["writeln"]("      }");
window["document"]["writeln"]("");
window["document"]["writeln"]("      @media (min-width: 768px) {");
window["document"]["writeln"]("        .bd-placeholder-img-lg {");
window["document"]["writeln"]("          font-size: 3.5rem;");
window["document"]["writeln"]("        }");
window["document"]["writeln"]("      }");
window["document"]["writeln"]("    </style>");
window["document"]["writeln"]("<style>");
window["document"]["writeln"]("/*");
window["document"]["writeln"](" * Globals");
window["document"]["writeln"](" */");
window["document"]["writeln"]("");
window["document"]["writeln"]("/* Links */");
window["document"]["writeln"]("a,");
window["document"]["writeln"]("a:focus,");
window["document"]["writeln"]("a:hover {");
window["document"]["writeln"]("  color: #fff;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"]("/* Custom default button */");
window["document"]["writeln"](".btn-secondary,");
window["document"]["writeln"](".btn-secondary:hover,");
window["document"]["writeln"](".btn-secondary:focus {");
window["document"]["writeln"]("  color: #333;");
window["document"]["writeln"]("  text-shadow: none; /* Prevent inheritance from `body` */");
window["document"]["writeln"]("  background-color: #fff;");
window["document"]["writeln"]("  border: .05rem solid #fff;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"]("");
window["document"]["writeln"]("/*");
window["document"]["writeln"](" * Base structure");
window["document"]["writeln"](" */");
window["document"]["writeln"]("");
window["document"]["writeln"]("html,");
window["document"]["writeln"]("body {");
window["document"]["writeln"]("  height: 100%;");
window["document"]["writeln"]("  background-color: #333;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"]("body {");
window["document"]["writeln"]("  display: -ms-flexbox;");
window["document"]["writeln"]("  display: flex;");
window["document"]["writeln"]("  color: #fff;");
window["document"]["writeln"]("  text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);");
window["document"]["writeln"]("  box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"](".cover-container {");
window["document"]["writeln"]("  max-width: 42em;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"]("");
window["document"]["writeln"]("/*");
window["document"]["writeln"](" * Header");
window["document"]["writeln"](" */");
window["document"]["writeln"](".masthead {");
window["document"]["writeln"]("  margin-bottom: 2rem;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"](".masthead-brand {");
window["document"]["writeln"]("  margin-bottom: 0;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"](".nav-masthead .nav-link {");
window["document"]["writeln"]("  padding: .25rem 0;");
window["document"]["writeln"]("  font-weight: 700;");
window["document"]["writeln"]("  color: rgba(255, 255, 255, .5);");
window["document"]["writeln"]("  background-color: transparent;");
window["document"]["writeln"]("  border-bottom: .25rem solid transparent;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"](".nav-masthead .nav-link:hover,");
window["document"]["writeln"](".nav-masthead .nav-link:focus {");
window["document"]["writeln"]("  border-bottom-color: rgba(255, 255, 255, .25);");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"](".nav-masthead .nav-link + .nav-link {");
window["document"]["writeln"]("  margin-left: 1rem;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"](".nav-masthead .active {");
window["document"]["writeln"]("  color: #fff;");
window["document"]["writeln"]("  border-bottom-color: #fff;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"]("@media (min-width: 48em) {");
window["document"]["writeln"]("  .masthead-brand {");
window["document"]["writeln"]("    float: left;");
window["document"]["writeln"]("  }");
window["document"]["writeln"]("  .nav-masthead {");
window["document"]["writeln"]("    float: right;");
window["document"]["writeln"]("  }");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"]("");
window["document"]["writeln"]("/*");
window["document"]["writeln"](" * Cover");
window["document"]["writeln"](" */");
window["document"]["writeln"](".cover {");
window["document"]["writeln"]("  padding: 0 1.5rem;");
window["document"]["writeln"]("}");
window["document"]["writeln"](".cover .btn-lg {");
window["document"]["writeln"]("  padding: .75rem 1.25rem;");
window["document"]["writeln"]("  font-weight: 700;");
window["document"]["writeln"]("}");
window["document"]["writeln"]("");
window["document"]["writeln"]("");
window["document"]["writeln"]("/*");
window["document"]["writeln"](" * Footer");
window["document"]["writeln"](" */");
window["document"]["writeln"](".mastfoot {");
window["document"]["writeln"]("  color: rgba(255, 255, 255, .5);");
window["document"]["writeln"]("}");
window["document"]["writeln"]("</style>");
