window["document"]["writeln"]("    <link rel=\'canonical\' href=\'https://getbootstrap.com/docs/4.4/examples/album/\'>");
window["document"]["writeln"]("    <link rel=\'stylesheet\' href=\'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\' integrity=\'sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\' crossorigin=\'anonymous\'>");
window["document"]["writeln"]("    <style>");
window["document"]["writeln"]("        .bd-placeholder-img {");
window["document"]["writeln"]("          font-size: 1.125rem;");
window["document"]["writeln"]("          text-anchor: middle;");
window["document"]["writeln"]("          -webkit-user-select: none;");
window["document"]["writeln"]("          -moz-user-select: none;");
window["document"]["writeln"]("          -ms-user-select: none;");
window["document"]["writeln"]("          user-select: none;");
window["document"]["writeln"]("        }");
window["document"]["writeln"]("  ");
window["document"]["writeln"]("        @media (min-width: 768px) {");
window["document"]["writeln"]("          .bd-placeholder-img-lg {");
window["document"]["writeln"]("            font-size: 3.5rem;");
window["document"]["writeln"]("          }");
window["document"]["writeln"]("        }");
window["document"]["writeln"]("        .nav_link a{");
window["document"]["writeln"]("           color: white;");
window["document"]["writeln"]("        }");
window["document"]["writeln"]("        .jumbotron {");
window["document"]["writeln"]("           margin-bottom: 0px;");
window["document"]["writeln"]("        }");
window["document"]["writeln"]("    </style>");
