//HTML-->JS http://tool.chinaz.com/Tools/Html_Js.aspx
document.writeln("<script src=\'https://code.jquery.com/jquery-3.3.1.slim.min.js\' integrity=\'sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\' crossorigin=\'anonymous\'></script>");
document.writeln("            <script src=\'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\' integrity=\'sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\' crossorigin=\'anonymous\'></script>");
document.writeln("            <script src=\'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\' integrity=\'sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\' crossorigin=\'anonymous\'></script>");
document.writeln("            <link rel=\'stylesheet\' href=\'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\' integrity=\'sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\' crossorigin=\'anonymous\'>");
document.writeln("<header class=\'navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar\' style=\'background-color: #563d7c;\'>");
document.writeln("<a class=\'navbar-brand mr-0 mr-md-2\' href=\'/\' aria-label=\'Bootstrap\'><svg xmlns=\'http://www.w3.org/2000/svg\' width=\'36\' height=\'36\' class=\'d-block\' viewBox=\'0 0 612 612\' role=\'img\' focusable=\'false\'><title>Bootstrap</title><path fill=\'currentColor\' d=\'M510 8a94.3 94.3 0 0 1 94 94v408a94.3 94.3 0 0 1-94 94H102a94.3 94.3 0 0 1-94-94V102a94.3 94.3 0 0 1 94-94h408m0-8H102C45.9 0 0 45.9 0 102v408c0 56.1 45.9 102 102 102h408c56.1 0 102-45.9 102-102V102C612 45.9 566.1 0 510 0z\'></path><path fill=\'currentColor\' d=\'M196.77 471.5V154.43h124.15c54.27 0 91 31.64 91 79.1 0 33-24.17 63.72-54.71 69.21v1.76c43.07 5.49 70.75 35.82 70.75 78 0 55.81-40 89-107.45 89zm39.55-180.4h63.28c46.8 0 72.29-18.68 72.29-53 0-31.42-21.53-48.78-60-48.78h-75.57zm78.22 145.46c47.68 0 72.73-19.34 72.73-56s-25.93-55.37-76.46-55.37h-74.49v111.4z\'></path></svg></a>");
document.writeln("");
document.writeln("<div class=\'navbar-nav-scroll\'>");
document.writeln("    <ul class=\'navbar-nav bd-navbar-nav flex-row\'>");
document.writeln("    <li class=\'nav-item\'>");
document.writeln("        <a class=\'nav-link \' href=\'/\' onclick=\'ga(\'send\', \'event\', \'Navbar\', \'Community links\', \'Bootstrap\');\'>Home</a>");
document.writeln("    </li>");
document.writeln("    <li class=\'nav-item\'>");
document.writeln("        <a class=\'nav-link active\' href=\'/docs/4.3/getting-started/introduction/\' onclick=\'ga(\'send\', \'event\', \'Navbar\', \'Community links\', \'Docs\');\'>Documentation</a>");
document.writeln("    </li>");
document.writeln("    <li class=\'nav-item\'>");
document.writeln("        <a class=\'nav-link \' href=\'/docs/4.3/examples/\' onclick=\'ga(\'send\', \'event\', \'Navbar\', \'Community links\', \'Examples\');\'>Examples</a>");
document.writeln("    </li>");
document.writeln("    <li class=\'nav-item\'>");
document.writeln("        <a class=\'nav-link\' href=\'https://themes.getbootstrap.com/\' onclick=\'ga(\'send\', \'event\', \'Navbar\', \'Community links\', \'Themes\');\' target=\'_blank\' rel=\'noopener\'>Themes</a>");
document.writeln("    </li>");
document.writeln("    <li class=\'nav-item\'>");
document.writeln("        <a class=\'nav-link\' href=\'https://expo.getbootstrap.com/\' onclick=\'ga(\'send\', \'event\', \'Navbar\', \'Community links\', \'Expo\');\' target=\'_blank\' rel=\'noopener\'>Expo</a>");
document.writeln("    </li>");
document.writeln("    <li class=\'nav-item\'>");
document.writeln("        <a class=\'nav-link\' href=\'https://blog.getbootstrap.com/\' onclick=\'ga(\'send\', \'event\', \'Navbar\', \'Community links\', \'Blog\');\' target=\'_blank\' rel=\'noopener\'>Blog</a>");
document.writeln("    </li>");
document.writeln("    </ul>");
document.writeln("</div>");
document.writeln("<a class=\'btn btn-bd-download d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3\' href=\'/docs/4.3/getting-started/download/\' style=\'color: white; float:right;\'>Download</a>");
document.writeln("</header>");
document.writeln("<style>");
document.writeln("    body {");
document.writeln("        font-family: \'Poppins\', sans-serif;");
document.writeln("    }");
document.writeln("    ");
document.writeln("    #sidebar a,#sidebar a:hover,#sidebar a:focus {");
document.writeln("        color: inherit;");
document.writeln("        text-decoration: none;");
document.writeln("        transition: all 0.3s;");
document.writeln("    }");
document.writeln("    ");
document.writeln("    #sidebar {");
document.writeln("        /* don\'t forget to add all the previously mentioned styles here too */");
document.writeln("        background: #7386D5;");
document.writeln("        color: #fff;");
document.writeln("        transition: all 0.3s;");
document.writeln("        height: 68vh;");
document.writeln("        overflow-y: scroll;");
document.writeln("    }");
document.writeln("    ");
document.writeln("    #sidebar .sidebar-header {");
document.writeln("        padding: 20px;");
document.writeln("        background: #6d7fcc;");
document.writeln("    }");
document.writeln("    ");
document.writeln("    #sidebar ul.components {");
document.writeln("        padding: 20px 0;");
document.writeln("        border-bottom: 1px solid #47748b;");
document.writeln("    }");
document.writeln("    ");
document.writeln("    #sidebar ul p {");
document.writeln("        color: #fff;");
document.writeln("        padding: 10px;");
document.writeln("    }");
document.writeln("    ");
document.writeln("    #sidebar ul li a {");
document.writeln("        padding: 10px;");
document.writeln("        font-size: 1.1em;");
document.writeln("        display: block;");
document.writeln("    }");
document.writeln("    #sidebar ul li a:hover {");
document.writeln("        color: #7386D5;");
document.writeln("        background: #fff;");
document.writeln("    }");
document.writeln("    ");
document.writeln("    #sidebar ul li.active > a, a[aria-expanded=\'true\'] {");
document.writeln("        color: #fff;");
document.writeln("        background: #6d7fcc;");
document.writeln("    }");
document.writeln("    ul ul a {");
document.writeln("        font-size: 0.9em !important;");
document.writeln("        padding-left: 30px !important;");
document.writeln("        background: #6d7fcc;");
document.writeln("    }");
document.writeln("</style>");
document.writeln("                  ");
document.writeln("<div class=\'col-12 col-md-3 col-xl-2 bd-sidebar\' style=\'padding-left: 0; float:left\'>");
document.writeln("<div class=\'wrapper\'>");
document.writeln("        <!-- Sidebar -->");
document.writeln("        <nav id=\'sidebar\'>");
document.writeln("            <div class=\'sidebar-header\'>");
document.writeln("                <h3>Bootstrap Sidebar</h3>");
document.writeln("            </div>");
document.writeln("    ");
document.writeln("            <ul class=\'list-unstyled components\'>");
document.writeln("                <li class=\'active\'>");
document.writeln("                    <a href=\'#homeSubmenu\' data-toggle=\'collapse\' aria-expanded=\'false\' class=\'dropdown-toggle\'>Home</a>");
document.writeln("                    <ul class=\'collapse list-unstyled\' id=\'homeSubmenu\'>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 1</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 2</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 3</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 4</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 5</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 6</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 7</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 8</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 9</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Home 10</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>About</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#pageSubmenu\' data-toggle=\'collapse\' aria-expanded=\'false\' class=\'dropdown-toggle\'>Pages</a>");
document.writeln("                    <ul class=\'collapse list-unstyled\' id=\'pageSubmenu\'>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Page 1</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Page 2</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'#\'>Page 3</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>Portfolio</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>Contact</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </nav>");
document.writeln("    ");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<style>");
document.writeln("        footer{");
document.writeln("          background-color: blueviolet;");
document.writeln("          position: fixed;");
document.writeln("          width: 100vw;");
document.writeln("          height: 20vh;");
document.writeln("          bottom: 50px;");
document.writeln("        }");
document.writeln("        footer a{");
document.writeln("          color:white;");
document.writeln("        }");
document.writeln("        .footer-copyright text-center py-3{");
document.writeln("         background-color: blueviolet;");
document.writeln("        }");
document.writeln("      </style>");
document.writeln("      <!-- Footer -->");
document.writeln("      <footer class=\'page-footer font-small indigo\'>");
document.writeln("      ");
document.writeln("          <!-- Footer Links -->");
document.writeln("          <div class=\'container text-center text-md-left\'>");
document.writeln("        ");
document.writeln("            <!-- Grid row -->");
document.writeln("            <div class=\'row\'>");
document.writeln("        ");
document.writeln("              <!-- Grid column -->");
document.writeln("              <div class=\'col-md-3 mx-auto\'>");
document.writeln("        ");
document.writeln("                <!-- Links -->");
document.writeln("                <h5 class=\'font-weight-bold text-uppercase mt-3 mb-4\'>Links</h5>");
document.writeln("        ");
document.writeln("                <ul class=\'list-unstyled\'>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Very long link 1</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Very long link 2</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Very long link 3</a>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("        ");
document.writeln("              </div>");
document.writeln("              <!-- Grid column -->");
document.writeln("        ");
document.writeln("              <hr class=\'clearfix w-100 d-md-none\'>");
document.writeln("        ");
document.writeln("              <!-- Grid column -->");
document.writeln("              <div class=\'col-md-3 mx-auto\'>");
document.writeln("        ");
document.writeln("                <!-- Links -->");
document.writeln("                <h5 class=\'font-weight-bold text-uppercase mt-3 mb-4\'>Links</h5>");
document.writeln("        ");
document.writeln("                <ul class=\'list-unstyled\'>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 1</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 2</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 3</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 4</a>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("        ");
document.writeln("              </div>");
document.writeln("              <!-- Grid column -->");
document.writeln("        ");
document.writeln("              <hr class=\'clearfix w-100 d-md-none\'>");
document.writeln("        ");
document.writeln("              <!-- Grid column -->");
document.writeln("              <div class=\'col-md-3 mx-auto\'>");
document.writeln("        ");
document.writeln("                <!-- Links -->");
document.writeln("                <h5 class=\'font-weight-bold text-uppercase mt-3 mb-4\'>Links</h5>");
document.writeln("        ");
document.writeln("                <ul class=\'list-unstyled\'>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 1</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 2</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 3</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 4</a>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("        ");
document.writeln("              </div>");
document.writeln("              <!-- Grid column -->");
document.writeln("        ");
document.writeln("              <hr class=\'clearfix w-100 d-md-none\'>");
document.writeln("        ");
document.writeln("              <!-- Grid column -->");
document.writeln("              <div class=\'col-md-3 mx-auto\'>");
document.writeln("        ");
document.writeln("                <!-- Links -->");
document.writeln("                <h5 class=\'font-weight-bold text-uppercase mt-3 mb-4\'>Links</h5>");
document.writeln("        ");
document.writeln("                <ul class=\'list-unstyled\'>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 1</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 2</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 3</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\'#!\'>Link 4</a>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("        ");
document.writeln("              </div>");
document.writeln("              <!-- Grid column -->");
document.writeln("        ");
document.writeln("            </div>");
document.writeln("            <!-- Grid row -->");
document.writeln("        ");
document.writeln("          </div>");
document.writeln("          <!-- Footer Links -->");
document.writeln("        ");
document.writeln("          <!-- Copyright -->");
document.writeln("          <div class=\'footer-copyright text-center py-3\'>© 2018 Copyright:");
document.writeln("            <a href=\'#\'> Bootstrap.com</a>");
document.writeln("          </div>");
document.writeln("          <!-- Copyright -->");
document.writeln("        ");
document.writeln("        </footer>");
document.writeln("        <!-- Footer -->");
